[package]
name = "timez"
version = "0.1.0"
edition = "2021"
description = "Time conversion utility"

[dependencies]
chrono = "0.4.38"
chrono-tz = "0.10.0"
clap = { version = "4.5.21", features = ["derive"] }
config = "0.14.1"
serde = { version = "1.0.215", features = ["derive"] }
